Task/rest controller
mariavv/AirportScheduleAPI_spring pull request #2
Opened 2020-11-10 13:36 UTC by mariavv

2020-11-17 19:17 UTC, Korgutlova requested changes
Исправить замечания

2020-11-17 19:17 UTC, Korgutlova commented on src/main/java/mariavv/airportscheduleapispring/domain/entity/FlightEntity.java
> +    //@Enumerated(EnumType.STRING)
удаляем неиспользуемый код

2020-11-17 19:17 UTC, Korgutlova commented on src/main/java/mariavv/airportscheduleapispring/service/FlightServiceImpl.java
> +    //@Resource(name="converters")
удаляем неиспользуемый код

2020-11-17 19:17 UTC, Korgutlova commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    airport_to_id           integer NOT NULL,
наверное нужно FK (для аэропортов) создать (если этого еще не было в предыдущих скриптах) то необходимо создать следующий скрипт с этими правками

2020-11-17 19:17 UTC, Korgutlova commented on src/main/java/mariavv/airportscheduleapispring/mapper/FlightMapper.java
> +        return null;
зачем нужно было создавать данный метод если он не реализован?

2020-11-17 19:17 UTC, Korgutlova commented on src/main/java/mariavv/airportscheduleapispring/controller/AirportController.java
> +        return airportService.getAirportByName(name);
почему метод возвращает Integer  а не AirportDto?

2020-11-17 19:17 UTC, Korgutlova commented on src/main/resources/db/migration/V1_0_0_1__init_script.sql
> +    postponed_on_flight_id  integer,
тоже самое вопрос про FK

2020-11-18 05:24 UTC, ramilmm commented on src/main/java/mariavv/airportscheduleapispring/repo/AirportRepository.java
> +public interface AirportRepository extends JpaRepository<AirportEntity, Integer> {
@Repository

2020-11-18 05:24 UTC, ramilmm commented on src/main/java/mariavv/airportscheduleapispring/repo/FlightRepository.java
> +public interface FlightRepository extends JpaRepository<FlightEntity, Integer> {
@Repository

2020-11-18 05:24 UTC, ramilmm commented on src/main/java/mariavv/airportscheduleapispring/service/AirportServiceImpl.java
> +    public Integer getAirportByName(String name) {
тут @Override не нужен?

2020-11-18 05:24 UTC, ramilmm commented on src/main/java/mariavv/airportscheduleapispring/service/AirportServiceImpl.java
> +    public AirportDto addAirport(AirportNameDto town) {
тут @Override не нужен?

2020-11-18 10:18 UTC, mariavv commented on src/main/java/mariavv/airportscheduleapispring/controller/AirportController.java
> +        return airportService.getAirportByName(name);
Это поиск записи бд по названию, больше ничего не нужно возвращать. AirportDto содержит только id и name.

2020-11-18 10:42 UTC, mariavv commented on src/main/java/mariavv/airportscheduleapispring/controller/FlightController.java
> +    @GetMapping()
Сделала /api/v1/flights

2020-11-18 10:43 UTC, mariavv commented on src/main/java/mariavv/airportscheduleapispring/controller/AirportController.java
> +    @GetMapping("/airports")
Сделала /api/v1/airports

2020-11-18 10:49 UTC, mariavv commented on src/main/java/mariavv/airportscheduleapispring/controller/FlightController.java
> +    @PutMapping
А зачем указывать url? Сейчас POST /api/v1/flights.

2020-11-18 13:46 UTC, ramilmm commented on src/main/java/mariavv/airportscheduleapispring/controller/AirportController.java
> +        return airportService.getAirportByName(name);
Если предполагается возвращать только айдишник записи в бд, то следует переименовать метод в какой-нибудь getAirportIdByName или что-то в этом роде. Если айдишник и название, то нужно возвращать какой-нибудь респонсентити с телом

2020-11-20 17:22 UTC, Korgutlova approved these changes
У меня больше замечаний нет. Готова принять PR.

2020-11-23 19:03 UTC, ramilmm commented
исправь мои небольшие замечания и можешь мёржить

2020-11-24 10:26 UTC, merged